### ISSUE TITLE
Closing a hyperbee?

### ISSUE THREAD

**Issue by martinheidegger** [mafintosh/hyperbee#6]
Is there a way for hyperbee to be closed?

**Comment by mafintosh** [comment]
Just close the feed you pass in

**Comment by RangerMauve** [comment]
Would a PR adding `.close` be welcome?

**Comment by martinheidegger** [comment]
Let me ask differently: is there a chance I break existing things if I close the hypercore at an inconvenient time?

**Comment by mafintosh** [comment]
No should be safe.
